[build]
  publish = "."

[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "/core/*"
  [headers.values]
    Cache-Control = "no-cache"

[[headers]]
  for = "/phases/*"
  [headers.values]
    Cache-Control = "no-cache"
