/* FramePro Mobile Web v3 */
(function(){
'use strict';
const mobile=/Android|iPhone|iPad|iPod|Mobile/i.test(navigator.userAgent||'')||(window.matchMedia&&matchMedia('(pointer:coarse)').matches);
if(!mobile)return;
const rootEl=document.documentElement;rootEl.classList.add('fp-web-mobile','fp-mobile','fp-mobile-v2','fp-true-mobile','fp-menu-open');
const style=document.createElement('style');style.textContent=`
html.fp-web-mobile,html.fp-web-mobile body{margin:0!important;width:100%!important;height:100%!important;overflow:hidden!important;touch-action:none!important;background:#000!important}
html.fp-web-mobile #gameShell{position:fixed!important;inset:0!important;transform:none!important;width:100dvw!important;height:100dvh!important;max-width:none!important;max-height:none!important;aspect-ratio:auto!important;border-radius:0!important}
html.fp-web-mobile #start{z-index:300000!important;pointer-events:auto!important;overflow:auto!important;touch-action:pan-y!important;padding:8px!important}
html.fp-web-mobile #start .startCard{position:relative!important;z-index:300001!important;pointer-events:auto!important;width:calc(100vw - 16px)!important;max-width:680px!important;margin:auto!important;padding:14px!important}
html.fp-web-mobile.fp-menu-open #fpWebMobileControls,html.fp-web-mobile.fp-menu-open #fpFullscreenBtn{display:none!important}
html.fp-web-mobile:not(.fp-menu-open) #fpWebMobileControls{display:block!important}
#fpWebMobileControls{position:fixed;inset:0;z-index:100000;pointer-events:none;touch-action:none}
#fpMoveJoy,#fpLookJoy,.fpWebBtn{pointer-events:auto;touch-action:none;user-select:none;-webkit-user-select:none}
.fpJoy{position:absolute;width:116px;height:116px;border-radius:50%;border:2px solid rgba(255,255,255,.38);background:rgba(8,15,24,.32);box-shadow:inset 0 0 20px rgba(0,0,0,.5)}
.fpJoyKnob{position:absolute;left:35px;top:35px;width:44px;height:44px;border-radius:50%;background:rgba(86,214,255,.7);border:2px solid rgba(255,255,255,.8)}
#fpMoveJoy{left:max(14px,env(safe-area-inset-left));bottom:max(14px,env(safe-area-inset-bottom))}
#fpLookJoy{right:max(96px,calc(env(safe-area-inset-right) + 88px));bottom:max(14px,env(safe-area-inset-bottom))}
html.fp-web-mobile.fp-sensor-on #fpLookJoy{opacity:.22;pointer-events:none!important}
.fpWebBtn{position:absolute;display:grid;place-items:center;border:1px solid rgba(255,255,255,.5);background:rgba(7,15,24,.8);color:#fff;border-radius:12px;font:800 10px system-ui;box-shadow:0 3px 14px rgba(0,0,0,.45)}
#fpPhotoBtn{right:max(16px,env(safe-area-inset-right));bottom:78px;width:66px;height:66px;border-radius:50%;font-size:27px;border:4px solid rgba(255,255,255,.85)}
#fpPauseBtn{right:62px;top:7px;width:40px;height:36px;font-size:16px}
#fpFullscreenBtn{position:fixed;right:10px;top:7px;width:42px;height:36px;z-index:100100;pointer-events:auto}
#fpSensorBtn{left:50%;bottom:12px;transform:translateX(-50%);min-width:132px;height:34px;padding:0 10px}
#fpCenterBtn{left:50%;bottom:52px;transform:translateX(-50%);min-width:90px;height:30px;padding:0 8px;display:none}
#fpLensMinus{right:64px;bottom:16px;width:36px;height:36px;border-radius:50%}#fpLensPlus{right:18px;bottom:16px;width:36px;height:36px;border-radius:50%}
#fpRotateGate{position:fixed;inset:0;z-index:400000;display:none;place-items:center;background:#05090f;color:#fff;text-align:center;padding:24px;font:800 19px system-ui}
html.fp-web-mobile.fp-playing.fp-portrait #fpRotateGate{display:grid}
#fpRotateGate button,#fpFullscreenMenu{margin-top:14px;padding:12px 16px;border:0;border-radius:12px;font-weight:900}
#fpFullscreenMenu{display:block;width:100%;background:#17334f;color:#fff}
html.fp-web-mobile #topbar{left:6px!important;right:108px!important;top:5px!important;height:34px!important;padding:3px 6px!important;z-index:90000!important}html.fp-web-mobile #brand{display:none!important}
html.fp-web-mobile .stats .chip{padding:3px 5px!important;font-size:8px!important}.fp-web-mobile .stats .chip:nth-child(2){display:none!important}
html.fp-web-mobile #exposureHud{top:5px!important;left:50%!important;transform:translateX(-50%)!important;min-width:190px!important;width:190px!important;padding:4px 7px!important;z-index:90010!important}.fp-web-mobile #exposureHud .expTitle,.fp-web-mobile #exposureHud .expAuto{display:none!important}.fp-web-mobile #exposureHud .expLabel{font-size:6px!important}.fp-web-mobile #exposureHud .expValue{font-size:11px!important}
html.fp-web-mobile #mission,html.fp-web-mobile #tips,html.fp-web-mobile #coveragePanel,html.fp-web-mobile #gallery,html.fp-web-mobile #heightControl,html.fp-web-mobile #bottom{display:none!important}
html.fp-web-mobile #alignmentPanel{left:7px!important;top:48px!important;bottom:auto!important;width:108px!important;padding:4px!important;gap:2px!important;z-index:80000!important}.fp-web-mobile #alignmentPanel .alignItem{padding:2px 4px!important;font-size:6.5px!important}.fp-web-mobile #alignmentPanel .liveBar{height:2px!important}
html.fp-web-mobile #miniMapPanel{right:7px!important;top:48px!important;width:112px!important;padding:4px!important;opacity:.72!important}.fp-web-mobile #miniMapCanvas{width:104px!important;height:70px!important}.fp-web-mobile #miniMapLegend{display:none!important}
@media(orientation:portrait){html.fp-web-mobile.fp-playing #gameShell{visibility:hidden!important}}
`;
document.head.appendChild(style);
const gate=document.createElement('div');gate.id='fpRotateGate';gate.innerHTML='<div><div style="font-size:64px">📱↻</div><div>Gire o celular para a horizontal.</div><button id="fpGateFs">TELA CHEIA</button></div>';document.body.appendChild(gate);
function key(code,down){dispatchEvent(new KeyboardEvent(down?'keydown':'keyup',{code,key:code.replace('Key','').toLowerCase(),bubbles:true}));}
function clickAny(ids){for(const id of ids){const e=document.getElementById(id);if(e){e.click();return;}}}
async function fullscreen(){try{if(!document.fullscreenElement&&document.documentElement.requestFullscreen)await document.documentElement.requestFullscreen({navigationUI:'hide'});}catch(_){}try{if(screen.orientation&&screen.orientation.lock)await screen.orientation.lock('landscape');}catch(_){}updateOrientation();}
function updateOrientation(){rootEl.classList.toggle('fp-portrait',innerHeight>innerWidth);}addEventListener('resize',updateOrientation);addEventListener('orientationchange',()=>setTimeout(updateOrientation,180));updateOrientation();
function makeJoy(id,look){const j=document.createElement('div');j.id=id;j.className='fpJoy';j.innerHTML='<div class="fpJoyKnob"></div>';let pid=null;const k=j.firstChild;let active={KeyW:false,KeyA:false,KeyS:false,KeyD:false};function move(e){if(pid!==e.pointerId)return;const r=j.getBoundingClientRect(),mx=r.width*.31;let x=e.clientX-r.left-r.width/2,y=e.clientY-r.top-r.height/2,l=Math.hypot(x,y)||1;if(l>mx){x=x/l*mx;y=y/l*mx;}k.style.transform=`translate(${x}px,${y}px)`;if(look){if(typeof window.__fpApplyLook==='function')window.__fpApplyLook(x*.055,y*.05);}else{const n={KeyW:y/mx<-.22,KeyS:y/mx>.22,KeyA:x/mx<-.22,KeyD:x/mx>.22};for(const c in n)if(n[c]!==active[c]){active[c]=n[c];key(c,n[c]);}}e.preventDefault();}function end(e){if(pid!==e.pointerId)return;pid=null;k.style.transform='translate(0,0)';if(!look)for(const c in active){if(active[c])key(c,false);active[c]=false;}}j.addEventListener('pointerdown',e=>{pid=e.pointerId;j.setPointerCapture(pid);move(e)},{passive:false});j.addEventListener('pointermove',move,{passive:false});j.addEventListener('pointerup',end);j.addEventListener('pointercancel',end);return j;}
function build(){if(document.getElementById('fpWebMobileControls'))return;const c=document.createElement('div');c.id='fpWebMobileControls';c.append(makeJoy('fpMoveJoy',false),makeJoy('fpLookJoy',true));c.insertAdjacentHTML('beforeend','<button class="fpWebBtn" id="fpPhotoBtn">📷</button><button class="fpWebBtn" id="fpPauseBtn">Ⅱ</button><button class="fpWebBtn" id="fpSensorBtn">📱 ATIVAR SENSORES</button><button class="fpWebBtn" id="fpCenterBtn">CENTRALIZAR</button><button class="fpWebBtn" id="fpLensMinus">−</button><button class="fpWebBtn" id="fpLensPlus">＋</button>');document.body.appendChild(c);document.getElementById('fpPhotoBtn').onclick=()=>clickAny(['captureBtn','fpPhotoBtn','mobileCaptureBtn']);document.getElementById('fpPauseBtn').onclick=()=>{key('Escape',true);setTimeout(()=>key('Escape',false),30)};const wheel=d=>(document.querySelector('canvas')||document.body).dispatchEvent(new WheelEvent('wheel',{deltaY:d,altKey:true,bubbles:true,cancelable:true}));document.getElementById('fpLensMinus').onclick=()=>wheel(120);document.getElementById('fpLensPlus').onclick=()=>wheel(-120);setupSensor();}
function setupSensor(){const b=document.getElementById('fpSensorBtn'),center=document.getElementById('fpCenterBtn');let enabled=false,last=null,zero=true,sy=0,sp=0;function norm(v){while(v>180)v-=360;while(v<-180)v+=360;return v;}function ori(e){if(!enabled||e.alpha==null)return;const angle=(screen.orientation&&screen.orientation.angle)||window.orientation||0;const pitch=Math.abs(angle)===90?(angle===90?e.gamma:-e.gamma):e.beta;const cur={yaw:e.alpha||0,pitch:pitch||0};if(zero||!last){last=cur;zero=false;return;}const dy=norm(cur.yaw-last.yaw),dp=cur.pitch-last.pitch;last=cur;if(Math.abs(dy)>18||Math.abs(dp)>18)return;sy=sy*.55+dy*.45;sp=sp*.55+dp*.45;}function tick(){if(enabled&&typeof window.__fpApplyLook==='function'){window.__fpApplyLook(sy*2.1,sp*1.8);sy*=.62;sp*=.62;}requestAnimationFrame(tick);}tick();b.onclick=async()=>{try{if(typeof DeviceOrientationEvent==='undefined')throw Error();if(typeof DeviceOrientationEvent.requestPermission==='function'){const p=await DeviceOrientationEvent.requestPermission();if(p!=='granted')throw Error();}enabled=!enabled;if(enabled){addEventListener('deviceorientationabsolute',ori,true);addEventListener('deviceorientation',ori,true);}else{removeEventListener('deviceorientationabsolute',ori,true);removeEventListener('deviceorientation',ori,true);}rootEl.classList.toggle('fp-sensor-on',enabled);b.textContent=enabled?'📱 SENSORES ON':'📱 ATIVAR SENSORES';center.style.display=enabled?'grid':'none';zero=true;last=null;}catch(_){b.textContent='⚠️ SENSOR BLOQUEADO';}};center.onclick=()=>{zero=true;last=null;sy=sp=0;};}
function menuState(){const s=document.getElementById('start');const open=!!s&&getComputedStyle(s).display!=='none'&&s.offsetParent!==null;rootEl.classList.toggle('fp-menu-open',open);rootEl.classList.toggle('fp-playing',!open);}
function bind(){build();const card=document.querySelector('#start .startCard');if(card&&!document.getElementById('fpFullscreenMenu')){const b=document.createElement('button');b.id='fpFullscreenMenu';b.textContent='⛶ JOGAR EM TELA CHEIA';b.onclick=e=>{e.preventDefault();fullscreen()};card.appendChild(b);}if(!document.getElementById('fpFullscreenBtn')){const b=document.createElement('button');b.id='fpFullscreenBtn';b.className='fpWebBtn';b.textContent='⛶';b.onclick=fullscreen;document.body.appendChild(b);}const gateBtn=document.getElementById('fpGateFs');if(gateBtn&&!gateBtn.__b){gateBtn.__b=1;gateBtn.onclick=fullscreen;}const start=document.getElementById('startBtn');if(start&&!start.__m){start.__m=1;start.addEventListener('click',fullscreen,true);}menuState();}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',bind,{once:true});else bind();setInterval(bind,500);const start=document.getElementById('start');if(start)new MutationObserver(menuState).observe(start,{attributes:true,attributeFilter:['style','class']});
})();